services:
  hd_coin_details:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/snippets:/etc/nginx/snippets
      - ./shared-folder/hd-coin-details:/usr/share/nginx/html
      - ./config/certs:/etc/ssl/certs
      - ./config/private:/etc/ssl/private
      - ./config/dhparam.pem:/etc/nginx/dhparam.pem
    ports:
      - 8101:80
      - 8444:443
    restart: unless-stopped
  main:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/snippets:/etc/nginx/snippets
      - ./shared-folder/main:/usr/share/nginx/html
      - ./config/certs:/etc/ssl/certs
      - ./config/private:/etc/ssl/private
      - ./config/dhparam.pem:/etc/nginx/dhparam.pem
    ports:
      - 8100:80
      - 8443:443
    restart: unless-stopped

