version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./shared-folder:/usr/share/nginx/html
    ports:
      - 8080:80

